CREATE TABLE aluno (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    cpf         VARCHAR(11)  NOT NULL,
    endereco    VARCHAR(255)
);

CREATE UNIQUE INDEX uk_aluno_email ON aluno (email);
CREATE UNIQUE INDEX uk_aluno_cpf ON aluno (cpf);
