CREATE TABLE disciplina (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(255) NOT NULL,
    curso_id    BIGINT       NOT NULL,
    ano         INTEGER      NOT NULL,
    periodo     INTEGER      NOT NULL,
    CONSTRAINT fk_disciplina_curso FOREIGN KEY (curso_id) REFERENCES curso (id)
);

CREATE INDEX idx_disciplina_curso_id ON disciplina (curso_id);
