CREATE TABLE turma (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disciplina_id   BIGINT       NOT NULL,
    vagas_totais    INTEGER      NOT NULL,
    vagas_ocupadas  INTEGER      NOT NULL DEFAULT 0,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ABERTA',
    CONSTRAINT fk_turma_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplina (id),
    CONSTRAINT ck_turma_vagas_totais CHECK (vagas_totais > 0),
    CONSTRAINT ck_turma_vagas_ocupadas CHECK (vagas_ocupadas >= 0 AND vagas_ocupadas <= vagas_totais),
    CONSTRAINT ck_turma_status CHECK (status IN ('ABERTA', 'FECHADA'))
);

CREATE INDEX idx_turma_disciplina_id ON turma (disciplina_id);
