CREATE TABLE matricula (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id          BIGINT       NOT NULL,
    turma_id          BIGINT       NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'PENDENTE',
    data_criacao      TIMESTAMP    NOT NULL,
    data_atualizacao  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_matricula_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id),
    CONSTRAINT fk_matricula_turma FOREIGN KEY (turma_id) REFERENCES turma (id),
    CONSTRAINT uk_matricula_aluno_turma UNIQUE (aluno_id, turma_id),
    CONSTRAINT ck_matricula_status CHECK (status IN ('PENDENTE', 'CONFIRMADA', 'CANCELADA'))
);

CREATE INDEX idx_matricula_aluno_id ON matricula (aluno_id);
CREATE INDEX idx_matricula_turma_id ON matricula (turma_id);
